owner: plantnet
repo: status

sites:
  - name: API (my.plantnet.org)
    url: https://my-api.plantnet.org/v2/languages?api-key=$MY_PLANTNET_API_KEY
    icon: https://image.flaticon.com/icons/png/512/1015/1015474.png
    assignees:
      - matcho
    headers:
      - "User-Agent: Upptime bot / github.com/plantnet/status"
  - name: Pl@ntNet Apps (include database)
    url: https://api.plantnet.org/v1/projects/weurope/observations
    assignees:
      - AntoineAA
    headers:
      - "User-Agent: Upptime bot / github.com/plantnet/status"
  - name: Image server
    url: https://bs.plantnet.org/image/o/e776015a3c885cd7ede6ee713115acb9665c37c5
    icon: https://image.flaticon.com/icons/png/512/1829/1829589.png
    assignees:
      - AntoineAA
    headers:
      - "User-Agent: Upptime bot / github.com/plantnet/status"
  - name: Identification engine
    url: https://api-test.plantnet.org/status/identification
    icon: https://image.flaticon.com/icons/png/512/2061/2061956.png
    assignees:
      - jclombar
    headers:
      - "User-Agent: Upptime bot / github.com/plantnet/status"

workflowSchedule:
  graphs: "0 * * * *"
  responseTime: "0 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 0 * * *" # Triggered by the GitHub Self Hosted Runner cron

runner: [self-hosted]

# Try to prevent the actions to delete issues
skipDeleteIssues: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain 
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://plantnet.org/wp-content/uploads/2021/07/plantnet_full.svg
  favicon: https://avatars.githubusercontent.com/u/2690110?s=60&v=4
  faviconSvg: https://plantnet.org/wp-content/uploads/2021/07/plantnet_icone_square.svg
  name: Pl@ntNet Status Page
  introTitle: ""
  introMessage: Uptime every 5 minutes, graph and response time every hour
  navbar:
    - title: API
      href: https://my.plantnet.org
    - title: Identify web
      href: https://identify.plantnet.org/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
